- name: bug
  color: d73a4a
  description: Something isn't working
  exclusive: false
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
  exclusive: false
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
  exclusive: false
- name: enhancement
  color: a2eeef
  description: New feature or request
  exclusive: false
- name: good first issue
  color: 7057ff
  description: Good for newcomers
  exclusive: false
- name: help wanted
  color: "008672"
  description: Extra attention is needed
  exclusive: false
- name: invalid
  color: e4e669
  description: This doesn't seem right
  exclusive: false
- name: question
  color: d876e3
  description: Further information is requested
  exclusive: false
- name: wontfix
  color: ffffff
  description: This will not be worked on
  exclusive: false
