assets: true
clone_addr: http://localhost:3000/Jhon/Mackerel
comments: true
description: ""
is_private: false
issues: true
labels: true
milestones: true
name: Mackerel
original_url: https://git.glassocean.hkn/Jhon/Mackerel
owner: Jhon
pulls: true
releases: true
service_type: 3
wiki: true
